### ISSUE TITLE
Add Controlled Sources to components library

### ISSUE THREAD

**Issue by diepala** [BondGraphTools/BondGraphTools#138]
I did not find how to make a source controlled by another variable of the graph, so I had to create my own components. Controlled sources are often used, for example in electrical circuits or control systems, although I am sure they are used in many other fields. For this reason I believe they should be added to the component libraries.

Here it is a library I made for the controlled sources:

```json
{
    "description": "Amplifier Components",
    "id":"amp",
    "components": {
      "Ae": {
        "description": "Effort Amplifier",
        "class": "Component",
        "metamodel": "Ae",
        "ports": {
          "0": {
            "description": "In"
          },
          "1": {
            "description": "Out"
          }
        },
        "params": {
          "ae" : {
            "description": "gain",
            "value": 1
          }
        },
        "constitutive_relations": [
          "e_1 - ae * e_0",
          "f_0"
        ]
      },
      "Af": {
        "description": "Flux Amplifier",
        "class": "Component",
        "metamodel": "Af",
        "ports": {
          "0": {
            "description": "In"
          },
          "1": {
            "description": "Out"
          }
        },
        "params": {
          "af" : {
            "description": "gain",
            "value": 1
          }
        },
        "constitutive_relations": [
          "f_1 + af * f_0",
          "e_0"
        ]
      }
    }
  }
```

Should this be included to the component libraries? Should these components be added to the base library or create a new one?

I called them amplifiers, but maybe controlled sources is a more adequate name. Also, the nomenclature may not be the best, so what do you think the names and descriptions should be?
 
Also, some people may need controlled sources that produce for example a controlled flux, given an effort, although this can be implemented with the previous controlled sources and a gyrator. Should these components also be included?

**Comment by peter-cudmore** [comment]
Hi diepala,

I would suggest having a read of [this review of bond graph modelling](https://ieeexplore.ieee.org/abstract/document/4140745). The TLDR is that effort and flow sources like a controlled current source or voltage source are in the standard library as 'Se' and 'Sf' components respectively.

Amplifiers, such as what you have described about are un-physical because the require infinite effort or flow. 
If you look at your constitutive relations for the effort amp, you must have $0 >= P_0 + P_1 =e_0*f_0 +e_1*f_1 = e_1(ae*f_0 - f_1)$. If we have equality, then you have re-created a transformer. If we have inequality, we have a transformer and a resistor of some variety.  

In practice, amplifiers are made up of nonlinear components such as transistors, which satisfy K.C.L and K.V.L and hence dissipate or store energy, not create it. 

Feel free to implement op-amps if you require them, but for the time being we'd like to keep all energy-injecting components in the base libraries as sources such as 'Sf' and 'Se' components.

Closing for now, but happy to revisit this later if there is enough interest.
